"""empty message

Revision ID: 82893dfe3b8a
Revises: 
Create Date: 2021-09-28 22:09:48.004184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82893dfe3b8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('instructions', sa.String(length=500), nullable=False),
    sa.Column('cook_time', sa.String(length=255), nullable=False),
    sa.Column('imageUrl', sa.String(length=100), nullable=False),
    sa.Column('originalUrl', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient')
    op.drop_table('recipe')
    # ### end Alembic commands ###
