"""empty message

Revision ID: a6a527ffbca6
Revises: 
Create Date: 2021-09-27 19:41:40.738339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a527ffbca6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('ingredients', sa.String(length=500), nullable=False),
    sa.Column('instructions', sa.String(length=500), nullable=False),
    sa.Column('cook_time', sa.Integer(), nullable=False),
    sa.Column('imageUrl', sa.String(length=100), nullable=False),
    sa.Column('originalUrl', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe')
    # ### end Alembic commands ###
